os: Visual Studio 2015

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  ruby_version: 22-x64
  TargetPath: sassc/bin/sassc
  matrix:
  - Compiler: msvc
    Config: Release
  - Compiler: msvc
    Config: Debug
  - Compiler: mingw
    Build: static
  - Compiler: mingw
    Build: shared

cache:
  - C:\Ruby%ruby_version%\lib\ruby\gems

install:
  - git clone https://github.com/sass/sassc.git
  - git clone https://github.com/sass/sass-spec.git
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ps: |
      if(!(gem which minitest 2>$nul)) { gem install minitest --no-ri --no-rdoc }
      if ($env:Compiler -eq "mingw" -AND -Not (Test-Path "C:\mingw64")) {
        # Install MinGW.
        $url  = "http://sourceforge.net/projects/mingw-w64/files/"
        $url += "Toolchains%20targetting%20Win64/Personal%20Builds/"
        $url += "mingw-builds/4.9.2/threads-win32/seh/"
        $url += "x86_64-4.9.2-release-win32-seh-rt_v3-rev0.7z/download"
        Invoke-WebRequest -UserAgent wget -Uri $url -OutFile x86_64-4.9.2-release-win32-seh-rt_v3-rev0.7z
        &7z x -oC:\ x86_64-4.9.2-release-win32-seh-rt_v3-rev0.7z > $null
      }
  - set PATH=C:\mingw64\bin;%PATH%
  - set CC=gcc

build_script:
  - ps: |
      if ($env:Compiler -eq "mingw") {
        mingw32-make -j4 sassc
      } else {
        msbuild /m:4 /p:Configuration=$env:Config sassc\win\sassc.sln
      }

      # print the branding art
      mv script/branding script/branding.ps1
      script/branding.ps1

      # print the version info
      &$env:TargetPath -v
      ruby -v

test_script:
  - ps: ruby sass-spec/sass-spec.rb -c $env:TargetPath -s --ignore-todo sass-spec/spec
